export const MARKDOWN_SAMPLE = [
  "# Kira Markdown Check",
  "",
  "这段用于检查 **粗体**、*斜体*、`inline code` 和 [外部链接](https://example.com)。",
  "",
  "## 列表",
  "- 普通列表项",
  "- [x] 已完成任务",
  "- [ ] 未完成任务",
  "",
  "1. 第一步",
  "2. 第二步",
  "",
  "> 引用块应该有左侧边线，并且颜色弱一点。",
  "",
  "## 表格",
  "| 功能 | 状态 | 备注 |",
  "| --- | --- | --- |",
  "| 代码块 | OK | 横向滚动 |",
  "| 表格 | OK | GFM |",
  "",
  "```ts",
  "function hello(name: string) {",
  "  return `hello ${name}`;",
  "}",
  "```"
].join("\n");
